version: "0.2"
ignorePaths:
  - archive
  - dist
  - node_modules
dictionaries:
  - en_US
  - softwareTerms
  - bash
  - node
  - npm
  - html
  - css
  - typescript
  - filetypes
words:
  - aistudio
  - bunchee
  - canonicalization
  - erniebot
  - fieldname
  - jiti
  - openai
  - preinstall
  - qianfan
  - tsdoc
  - yinian
ignoreWords:
  - zhengxs
